preview <- read.table("household_power_consumption.txt", sep = ";", stringsAsFactors = FALSE, na.strings = "?", header = TRUE, nrows = 50)
classes <- sapply(preview, class)
df <- read.table("household_power_consumption.txt", sep = ";", stringsAsFactors = FALSE, na.strings = "?", header = TRUE, colClasses = classes)
dfcomplete <- df[complete.cases(df),]
dfcomplete$Time <- strptime(paste(dfcomplete$Date, dfcomplete$Time), "%e/%m/%Y %H:%M:%S")
dfcomplete$Date <- as.Date(dfcomplete$Date, "%e/%m/%Y")
starttime <- as.Date("01/02/2007", "%e/%m/%Y")
endtime <- as.Date("02/02/2007", "%e/%m/%Y")
d <- dfcomplete[(dfcomplete$Date >= starttime & dfcomplete$Date <= endtime), ]
par(mfrow = c(2,2))
plot(d$Time, d$Global_active_power, type='l', xlab = NA, ylab = "Global Active Power")
plot(d$Time, d$Voltage, type='l', xlab = "datetime", ylab = "Voltage")
plot(d$Time, d$Sub_metering_1, type='n', xlab = NA, ylab = "Energy sub metering")
points(d$Time, d$Sub_metering_1, type='l')
points(d$Time, d$Sub_metering_2, type='l', col = "red")
points(d$Time, d$Sub_metering_3, type='l', col = "blue")
legend("topright", lwd = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), cex = 0.8)
plot(d$Time, d$Global_reactive_power , type='l', xlab = "datetime", ylab = "Global_reactive_power")
dev.copy(png, file="plot4.png")
dev.off()